{
 "title": "Dashboard_bank",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Бизнес", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Оборот банка",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(amount) FROM default.logs WHERE event = 'processed'"
    }
   ]
  },
  {
   "title": "Поток документов",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    countIf(event = 'new_document') as \"1. Клиент (Вход)\",\r\n    countIf(event = 'doc_received') as \"2. Шлюз (GWFI)\",\r\n    countIf(event = 'processed') as \"3. Адаптер (Успех)\",\r\n    countIf(event = 'security_alert') as \"4. Блокировано (Атака)\"\r\nFROM default.logs\r\nWHERE timestamp >= ($__from / 1000)"
    }
   ]
  },
  {
   "title": "Топ 5 активных клиентов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    client_id,\r\n    sum(amount) as total_volume\r\nFROM default.logs\r\nWHERE event = 'processed'\r\n  AND timestamp >= ($__from / 1000)\r\nGROUP BY client_id\r\nORDER BY total_volume DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Журнал атак",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toDateTime(toUInt64(timestamp)) as \"Время\",\r\n    client_id as \"Атакующий (ИНН)\",\r\n    reason as \"Причина\",\r\n    payload as \"Пейлоад (SQL)\"\r\nFROM default.logs\r\nWHERE event = 'security_alert'\r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  { "title": "Очереди", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Очередь документов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toDateTime(toUInt64(timestamp)) as time,\r\n    doc_id,\r\n    service,\r\n    event\r\nFROM default.logs\r\nWHERE event = 'doc_received' OR event = 'processed'\r\nORDER BY timestamp DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "EPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(bank_app_events_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Задержка на шардах",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toDateTime(toUInt64(timestamp / 5) * 5) as time,\r\n    concat('Shard #', toString(shard_id)) as shard,\r\n    avg(processing_time) as latency\r\nFROM default.logs\r\nWHERE service = 'adapter' AND event = 'processed' AND timestamp >= ($__from / 1000)\r\nGROUP BY time, shard ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "График очередей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (consumergroup) (kafka_consumergroup_lag)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  { "title": "Инфраструктура", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Статусы сервисов",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT time, service, max(val) as status FROM (\r\n    SELECT toDateTime(toUInt64(timestamp / 5) * 5) as time, service, 1 as val\r\n    FROM default.logs WHERE timestamp >= ($__from / 1000) GROUP BY time, service\r\n    UNION ALL\r\n    SELECT toDateTime(toUInt64(timestamp / 5) * 5) as time, 'generator' as service, 0 as val\r\n    FROM default.logs WHERE timestamp >= ($__from / 1000)\r\n    UNION ALL\r\n    SELECT toDateTime(toUInt64(timestamp / 5) * 5) as time, 'gwfi' as service, 0 as val\r\n    FROM default.logs WHERE timestamp >= ($__from / 1000)\r\n    UNION ALL\r\n    SELECT toDateTime(toUInt64(timestamp / 5) * 5) as time, 'adapter' as service, 0 as val\r\n    FROM default.logs WHERE timestamp >= ($__from / 1000)\r\n) GROUP BY time, service ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(host_memory_used_bytes / host_memory_total_bytes) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}